context:
  name: toml11
  version: "4.4.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/ToruNiina/toml11/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 815bfe6792aa11a13a133b86e7f0f45edc5d71eb78f5fb6686c49c7f792b9049

build:
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - if: unix
      then: make
    - if: win
      then: ninja

tests:
  - package_contents:
      include:
        - toml.hpp
      files:
        - ${{ "Library/" if win else "" }}lib/cmake/toml11/toml11Config.cmake

about:
  homepage: https://github.com/ToruNiina/toml11?tab=readme-ov-file#toml11
  summary: 'TOML for Modern C++'
  description: |
    toml11 is a feature-rich TOML language library for C++11/14/17/20.
  license: MIT
  license_file: LICENSE
  documentation: https://toruniina.github.io/toml11/
  repository: https://github.com/ToruNiina/toml11

extra:
  recipe-maintainers:
    - ax3l
